apiVersion: v1
kind: Service
metadata:
  name: hellopython-service
spec:
  ports:
  - protocol: TCP
    name: "7000"
    port: 7000
    targetPort: 7000
  type: LoadBalancer
  selector:
    app: hellopython
status:
  loadBalancer: {}
